import "react-loading-skeleton/dist/skeleton.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/variables.css";
import "@/styles/globals.css";
import ProgressBar from "@/components/primitives/progress-bar";
import { NuqsAdapter } from "nuqs/adapters/next";
import { Toaster } from "sonner";
import Sidebar from "@/components/primitives/sidebar/sidebar";
import { twJoin } from "tailwind-merge";

const geistSans = localFont({
  src: "../../public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "../../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={twJoin(
          "flex h-dvh flex-col bg-primary font-sans text-primary antialiased md:flex-row",
          "purple",
          geistSans.variable,
          geistMono.variable,
        )}
      >
        <ProgressBar />
        <Toaster
          toastOptions={{
            className: "w-full z-[100000]",
          }}
          containerAriaLabel="sonner-toast"
        />
        <NuqsAdapter>
          <Sidebar />
          {children}
        </NuqsAdapter>
      </body>
    </html>
  );
}
